name: GitHub-Profile-3D-Contrib

on:
  schedule: # Dijadwalkan jalan setiap jam 6 pagi UTC
    - cron: "0 18 * * *"
  workflow_dispatch: # Agar bisa dijalankan manual tombol klik

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_3D }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
